name: Migrate TAR

on:
  workflow_dispatch:
    inputs:
      app_name:
        type: string
        required: true
      starts_with:
        type: string
      limit:
        type: number

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Migrate
        run: |
          set -eux
          cd ${{ inputs.app_name }}

          count=0
          for v in ${{ inputs.starts_with }}*/; do
            if [ $count = ${{ inputs.limit }} ] then
              break
            fi
          
            VERSION=$(echo $v | cut -d/ -f1)
            tar -czvf "$VERSION".tar.gz --directory "$VERSION" .
            rm -rf ./"$VERSION"/

            (( count += 1 ))
          done

          ls -la

          git add .
          git commit -m "Migrate ${{ inputs.app_name }} to tar.gz"
          git push
