name: Release TAR

on:
  workflow_call:
    inputs:
      app_name:
        type: string
        required: true
      version:
        type: string
        required: true
      environment:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      app_name:
        description: App
        required: true
      version:
        description: Version
        required: true
      environment:
        type: choice
        description: Environment (UAT/PRD)
        options:
          - PRD
          - UAT
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Release
        uses: railmapgen/releaser@main
        with:
          app_name: ${{ inputs.app_name }}
          version: ${{ inputs.version }}
          env: ${{ inputs.environment }}

      - name: Release to other mirrors
        if: ${{ github.event.inputs.environment == 'PRD' }}
        run: |
          curl -XPOST -u "wongchito:${{ secrets.RMG_BUILD_AND_RELEASE }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/uat-railmapgen/rmg-repositories/actions/workflows/release-gitlab.yml/dispatches \
            --data '{"ref": "main", "inputs": {"app_name": "${{ github.event.inputs.app_name }}", "version": "${{ github.event.inputs.version }}"}}'
          # curl -XPOST -u "wongchito:${{ secrets.RMG_BUILD_AND_RELEASE }}" \
          #   -H "Accept: application/vnd.github.everest-preview+json" \
          #   -H "Content-Type: application/json" \
          #   https://api.github.com/repos/uat-railmapgen/rmg-repositories/actions/workflows/release-bitbucket.yml/dispatches \
          #   --data '{"ref": "main", "inputs": {"app_name": "${{ github.event.inputs.app_name }}", "version": "${{ github.event.inputs.version }}"}}'
