name: Release to GitHub

on:
  workflow_call:
    inputs:
      app_name:
        type: string
        required: true
      version:
        type: string
        required: true
      environment:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      app_name:
        description: App
        required: true
      version:
        description: Version
        required: true
      environment:
        type: choice
        description: Environment (UAT/PRD)
        options:
          - PRD
          - UAT
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Parse org and repo
        shell: bash
        run: |
          if [ ${{ inputs.environment }} == 'PRD' ]
          then
            echo "org=railmapgen" >> "$GITHUB_ENV"
            echo "repo=${{ inputs.app_name }}" >> "$GITHUB_ENV"
          else
            echo "org=uat-railmapgen" >> "$GITHUB_ENV"
            if [ ${{ inputs.app_name }} == 'railmapgen.github.io' ]
            then
              echo "repo=uat-railmapgen.github.io" >> "$GITHUB_ENV"
            else
              echo "repo=${{ inputs.app_name }}" >> "$GITHUB_ENV"
            fi
          fi

      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.org }}/${{ env.repo }}
          path: target
          token: ${{ secrets.RMG_BUILD_AND_RELEASE }}
          fetch-depth: 0

      - name: Git config
        shell: bash
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Release
        shell: bash
        run: |
          set -eux
          # Checkout to gh-pages branch
          cd target/
          { git checkout gh-pages; } || { git checkout -b gh-pages; }
          
          # Clear folder
          cd ..
          rm -rf target/*
          
          # Download artifacts
          curl -o dist.tar.gz "$(echo 'https://github.com/uat-railmapgen/rmg-repositories/raw/main/${{ inputs.app_name }}/${{ inputs.version }}.tar.gz' | sed 's/#/%23/g')" -L
          tar -xvf dist.tar.gz -C target/
          
          # Bypass JEKYLL
          touch target/.nojekyll
          
          # Write INFO.JSON
          cat >target/info.json <<EOF
          {
            "component": "${{ inputs.app_name }}",
            "version": "${{ inputs.version }}",
            "environment": "${{ inputs.environment }}",
            "instance": "GitHub"
          }
          EOF
          
          # Push
          cd target
          git add .
          git commit -m "Release version ${{ inputs.version }} to ${{ inputs.environment }}"
          git push -u origin gh-pages

