name: Release to Bitbucket

on:
  workflow_call:
    inputs:
      app_name:
        type: string
        required: true
      version:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      app_name:
        description: App
        required: true
      version:
        description: Version
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Prepare PRD repo
        run: |
          git clone https://chitowong:${{ secrets.BITBUCKET_RELEASE }}@bitbucket.org/railmapgen/railmapgen.bitbucket.io.git BITBUCKET_REPO/

      - name: Release
        run: |
          chmod +x ./release-bitbucket.sh
          ./release-bitbucket.sh ${{ github.event.inputs.app_name }} ${{ github.event.inputs.version }}
