name: Release

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: App
        required: true
      version:
        description: Version
        required: true
      environment:
        description: Environment (UAT/PRD)
        default: UAT
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "RMG Release Agent"
          git config --global user.email rmg.release.agent@users.noreply.github.com

      - name: Prepare UAT repo
        if: ${{ github.event.inputs.environment == 'UAT' }}
        run: |
          if [ ${{ github.event.inputs.app_name }} == 'railmapgen.github.io' ]
          then
            git clone https://wongchito:${{ secrets.RMG_BUILD_AND_RELEASE }}@github.com/uat-railmapgen/uat-railmapgen.github.io.git TARGET_REPO/
          else
            git clone https://wongchito:${{ secrets.RMG_BUILD_AND_RELEASE }}@github.com/uat-railmapgen/${{ github.event.inputs.app_name }}.git TARGET_REPO/
          fi

      - name: Prepare PRD repo
        if: ${{ github.event.inputs.environment == 'PRD' }}
        run: |
          git clone https://wongchito:${{ secrets.RMG_BUILD_AND_RELEASE }}@github.com/railmapgen/${{ github.event.inputs.app_name }}.git TARGET_REPO/

      - name: Release
        run: |
          chmod +x ./release.sh
          ./release.sh ${{ github.event.inputs.app_name }} ${{ github.event.inputs.version }} ${{ github.event.inputs.environment }}
