name: Release

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: App
        required: true
      version:
        description: Version
        required: true
      environment:
        description: Environment (UAT/PRD)
        default: UAT
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "RMG Release Agent"
          git config --global user.email rmg.release.agent@users.noreply.github.com

      - name: Prepare UAT repo
        if: ${{ github.event.inputs.environment == 'UAT' }}
        run: |
          git clone --depth 1 https://wongchito:${{ secrets.RMG_BUILD_AND_RELEASE }}@github.com/uat-railmapgen/rmg-palette.git TARGET_REPO/

      - name: Prepare PRD repo
        if: ${{ github.event.inputs.environment == 'PRD' }}
        run: |
          git clone --depth 1 https://wongchito:${{ secrets.RMG_BUILD_AND_RELEASE }}@github.com/railmapgen/rmg-palette.git TARGET_REPO/

      - name: Release
        run: |
          chmod +x ./release.sh
          ./release.sh
